[workspace]
resolver = "3"
members = ["crates/*", "apps/gravity", "apps/ecp-life2"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
fathom-core = { path = "crates/fathom-core" }
fathom-shell = { path = "crates/fathom-shell" }
gravity = { path = "apps/gravity" }
ecp-life2 = { path = "apps/ecp-life2" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
